apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: u8u1xd83d-go 
  janus-idp.io/tekton: u8u1xd83d-go
  backstage.io/kubernetes-id: u8u1xd83d-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: u8u1xd83d-go
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  